server:
  port: 8087

spring:
  application:
    name: notification-service
  data:
    mongodb:
      uri: mongodb://mongo:27017/notificationdb

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/