server:
  port: 8083

spring:
  application:
    name: catalog-service
  data:
    mongodb:
      uri: mongodb://mongo:27017/catalogdb
  jackson:
    serialization:
      indent_output: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/