server:
  port: 8085

spring:
  application:
    name: recommendation-service
  elasticsearch:
    uris: http://elasticsearch:9200

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/