server:
  port: 8086

spring:
  application:
    name: cart-service
  data:
    redis:
      host: redis
      port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/